-- Up
CREATE TABLE IF NOT EXISTS BanGuilds (
  ID TEXT NOT NULL PRIMARY KEY,
  REASON TEXT NOT NULL,
  BanStatus BOOLEAN NOT NULL DEFAULT true,
  Warns NUMBER NOT NULL DEFAULT 1
);

-- Down
Drop TABLE BanGuils